# Generated by Django 4.2 on 2024-07-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=5)),
                ('file', models.FileField(upload_to='media/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
